name: github pages

on:
  push:
    branches:
      - main # default branch

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run export
      - run: touch ./out/.nojekyll
      - run: echo "zhangyuyan.cn" > ./out/CNAME
      - run: echo "3248229739272028049" > ./out/tencent1796729923384981875.txt

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
